<?php

namespace PozarniPoplach;

use Janmensik\Jmlib\Database;
use Janmensik\Jmlib\Modul;

/**
 * Class DeviceAuth
 * Handles OAuth 2.0 Device Flow for Kiosk devices (Raspberry Pi).
 * Links physical devices to Firefighter Units via mobile authorization.
 */
class DeviceAuth extends Modul {
    /**
     * DeviceAuth constructor.
     * @param Database $database
     */
    public function __construct(Database &$database) {
        parent::__construct($database);
    }

    /**
     * Phase 1: Initialize a new device auth session.
     * Creates a temporary record that the Kiosk will poll.
     *
     * @param string $deviceUuid Hardware UUID generated by the kiosk.
     * @return array|null The device code and metadata, or null on failure.
     */
    public function initSession(string $deviceUuid): array|null {
        // Cleanup expired sessions first (Garbage Collection)
        $this->DB->query('DELETE FROM alarm_device_session WHERE expires_at < NOW()', __METHOD__ . ' cleanup');

        $deviceCode = $this->generateUserFriendlyCode(8);
        $expiresAt = date('Y-m-d H:i:s', strtotime('+5 minutes'));

        $query = 'INSERT INTO alarm_device_session (device_code, device_uuid, status, expires_at)
                  VALUES ("' . mysqli_real_escape_string($this->DB->db, $deviceCode) . '",
                          "' . mysqli_real_escape_string($this->DB->db, $deviceUuid) . '",
                          "pending",
                          "' . $expiresAt . '")';

        if ($this->DB->query($query, __METHOD__)) {
            return [
                'device_code' => $deviceCode,
                'expires_at' => $expiresAt,
                // The URL where firefighter logs in on mobile
                'verification_url' => $this->getVerificationUrl($deviceCode)
            ];
        }

        return null;
    }

    /**
     * Generates a short, user-friendly code excluding ambiguous characters.
     */
    private function generateUserFriendlyCode(int $length = 8): string {
        // Excluded: 0, O (looks like 0), 1, l (looks like 1), I (looks like 1/l)
        $alphabet = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
        $code = '';
        $max = strlen($alphabet) - 1;
        for ($i = 0; $i < $length; $i++) {
            $code .= $alphabet[random_int(0, $max)];
        }
        return $code;
    }

    /**
     * Phase 2: Poll session status.
     * Called by the Kiosk every few seconds.
     *
     * @param string $deviceCode The code returned by initSession.
     * @return array|null Current status and data, or null if expired/not found.
     */
    public function checkSessionStatus(string $deviceCode): array|null {
        $query = 'SELECT status, unit_id, device_uuid FROM alarm_device_session
                  WHERE device_code = "' . mysqli_real_escape_string($this->DB->db, $deviceCode) . '"
                  AND expires_at > NOW() LIMIT 1';

        $row = $this->DB->getRow($this->DB->query($query, __METHOD__));
        return $row ?: null;
    }

    /**
     * Phase 3: Link a session to a unit.
     * Called by the Mobile phone after successful login.
     *
     * @param string $deviceCode The code scanned from the QR.
     * @param int $unitId The ID of the unit to authorize this device for.
     * @param string|null $deviceName Optional name for the device.
     * @return bool Success status.
     */
    public function linkSessionToUnit(string $deviceCode, int $unitId, ?string $deviceName = null): bool {
        $query = 'UPDATE alarm_device_session
                  SET status = "linked", unit_id = ' . intval($unitId) . ',
                      device_name = "' . mysqli_real_escape_string($this->DB->db, $deviceName) . '"
                  WHERE device_code = "' . mysqli_real_escape_string($this->DB->db, $deviceCode) . '"
                  AND status = "pending" AND expires_at > NOW()';

        return (bool)$this->DB->query($query, __METHOD__);
    }

    /**
     * Phase 4: Complete authorization.
     * Generates permanent refresh token and moves device to authorized list.
     *
     * @param string $deviceCode The finalized code.
     * @return array|null The permanent refresh token and unit info, or null.
     */
    public function authorizeDevice(string $deviceCode): array|null {
        $session = $this->checkSessionStatusWithExtraFields($deviceCode);

        if ($session && $session['status'] === 'linked' && !empty($session['unit_id'])) {
            $refreshToken = bin2hex(random_bytes(32));
            $refreshTokenHash = hash('sha256', $refreshToken);

            // Move to authorized table
            $query = 'INSERT INTO alarm_device_authorized (device_uuid, unit_id, device_name, refresh_token_hash)
                      VALUES ("' . mysqli_real_escape_string($this->DB->db, $session['device_uuid']) . '",
                              ' . intval($session['unit_id']) . ',
                              "' . mysqli_real_escape_string($this->DB->db, $session['device_name']) . '",
                              "' . mysqli_real_escape_string($this->DB->db, $refreshTokenHash) . '")
                      ON DUPLICATE KEY UPDATE
                              unit_id = VALUES(unit_id),
                              device_name = VALUES(device_name),
                              refresh_token_hash = VALUES(refresh_token_hash),
                              last_seen = NOW()';

            if ($this->DB->query($query, __METHOD__)) {
                // Remove the temporary session immediately
                $this->DB->query('DELETE FROM alarm_device_session WHERE device_code = "' . mysqli_real_escape_string($this->DB->db, $deviceCode) . '"');

                return [
                    'refresh_token' => $refreshToken,
                    'unit_id' => $session['unit_id']
                ];
            }
        }

        return null;
    }

    /**
     * Internal helper to get session status with more fields.
     */
    private function checkSessionStatusWithExtraFields(string $deviceCode): array|null {
        $query = 'SELECT status, unit_id, device_uuid, device_name FROM alarm_device_session
                  WHERE device_code = "' . mysqli_real_escape_string($this->DB->db, $deviceCode) . '"
                  AND expires_at > NOW() LIMIT 1';

        $row = $this->DB->getRow($this->DB->query($query, __METHOD__));
        return $row ?: null;
    }

    /**
     * Helper to get device credentials from headers or request.
     * Token is ONLY accepted from Authorization or X-Device-Token header.
     * UUID is accepted from X-Device-UUID header or request parameter.
     */
    public function getRequestCredentials(): array {
        $headers = [];
        foreach ($_SERVER as $name => $value) {
            if (substr($name, 0, 5) == 'HTTP_') {
                $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
            }
        }

        $uuid = $headers['X-Device-Uuid'] ?? $_REQUEST['uuid'] ?? null;

        $token = null;
        if (isset($headers['Authorization']) && preg_match('/Bearer\s+(.*)$/i', $headers['Authorization'], $matches)) {
            $token = $matches[1];
        } elseif (isset($headers['X-Device-Token'])) {
            $token = $headers['X-Device-Token'];
        }

        return [
            'uuid' => $uuid,
            'token' => $token
        ];
    }

    /**
     * Validates a refresh token and updates the device's last_seen timestamp.
     *
     * @param string $deviceUuid The hardware UUID.
     * @param string $refreshToken The raw refresh token from the device.
     * @return int|null Authorized Unit ID if valid, or null.
     */
    public function validateDevice(string $deviceUuid, string $refreshToken): int|null {
        $query = 'SELECT unit_id, refresh_token_hash FROM alarm_device_authorized
                  WHERE device_uuid = "' . mysqli_real_escape_string($this->DB->db, $deviceUuid) . '" LIMIT 1';

        $device = $this->DB->getRow($this->DB->query($query, __METHOD__));

        if ($device && hash_equals($device['refresh_token_hash'], hash('sha256', $refreshToken))) {
            // Update last seen
            $this->DB->query('UPDATE alarm_device_authorized SET last_seen = NOW()
                              WHERE device_uuid = "' . mysqli_real_escape_string($this->DB->db, $deviceUuid) . '"');
            return (int)$device['unit_id'];
        }

        return null;
    }

    /**
     * Helper to generate the mobile activation URL.
     */
    private function getVerificationUrl(string $deviceCode): string {
        $baseUrl = $_ENV['ABSOLUTE_URL'] ?? '';
        return $baseUrl . '/activate?code=' . $deviceCode;
    }
}
