# global variables
APP_ADMIN_EMAIL = "jan.mensik@gmail.com"; # email spravce (nas)
APP_EMAIL = "info@poyarnipoplach.cz";
APP_BRAND = "Požární Poplach";
APP_BRAND_LOGO = "favicon.svg";
APP_URL = "https://www.pozarnipoplach.cz";
APP_NAME = "Požární poplach Back Office";
APP_SHORTNAME = 'PP BO';
APP_NAME_APPENDIX = "Back Office";

GLOBAL_CURRENCY = "Kč";
GLOBAL_PAGINATION_PREV = "Předchozí";
GLOBAL_PAGINATION_NEXT = "Další";
GLOBAL_PAGINATION_DOTS = "…";
GLOBAL_LEVEL = "Úroveň";

[pages]
# array 'page' of pages
page = dashboard
page = users
page = settings
page = units
page = dispatches

page = reservations
page = reservation
page = reservation-edit
page = pricelists
page = pricelist-edit
page = closures
page = gatecodes
page = gatecode-edit
page = partners
page = partner-edit
page = alarm

# set of vars for each page
dashboard_title = "Přehled"
dashboard_url = 
dashboard_icon = "fa-regular fa-house-blank"

transfers_title = "Transfery"
transfers_url = transfers
transfers_icon = "fa-regular fa-van-shuttle"

users_title = "Uživatelé"
users_url = users
users_icon = "fa-regular fa-users"

settings_title = "Nastavení uživatele"
settings_url = settings
settings_icon = "fa-regular fa-users"
settings_parent = users

units_title = "Jednotky"
units_url = units
units_icon = "fa-regular fa-building-shield"
units_create = "Vytvořit jednotku"
units_edit_title = "Jednotka"

dispatches_title = "Výjezdy"
dispatches_url = dispatches
dispatches_icon = "fa-regular fa-truck-arrow-right"

devices_title = "Terminály"
devices_url = devices
devices_icon = "fa-solid fa-tv"
devices_edit_title = "Terminál"

vehicle_types_title = "Typy vozidel"
vehicle_types_url = vehicle-types
vehicle_types_icon = "fa-solid fa-bus-simple"
vehicle_types_edit_title = "Editace typu vozidla"
vehicle_types_create = "Nový typ vozidla"

event_types_title = "Typy událostí"
event_types_url = event-types
event_types_icon = "fa-solid fa-calendar-exclamation"
event_types_edit_title = "Editace typu události"
event_types_create = "Nový typ události"

advertisers_title = "Inzerenti"
advertisers_url = advertisers
advertisers_icon = "fa-solid fa-briefcase"
advertisers_create = "Nový inzerent"
advertisers_edit_title = "Inzerent"

ads_title = "Reklamy"
ads_url = ads
ads_icon = "fa-regular fa-billboard"
ads_create = "Nová reklama"
ads_edit_title = "Reklama"

reservations_title = "Rezervace"
reservations_url = reservations
reservations_icon = "fa-regular fa-ticket-perforated"

reservation_create = "Nová rezervace"

reservation_title = "Rezervace"
reservation_parent = reservations
reservation_edit_title = "Editace rezervace"

statistic_title = "Statistika"
statistic_url = statistic
statistic_icon = "fa-regular fa-chart-line"

mail_schedule_title = "Emailing Front"
mail_schedule_url = mail-schedule
mail_schedule_icon = "fa-regular fa-mailbox-flag-up"

search_url = search

alarm_title = "Poplachy"
alarm_url = dispatch